/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendApprovalEmail': ApiRouteHandler<{ requestId: string }, unknown, { topic: 'content.email_requested'; data: { requestId: string } }>
    'PublishContent': EventHandler<{ requestId: string; userEmail: string; handles?: { devto?: string; x?: string; linkedin?: string } }, never>
    'TriggerPublish': ApiRouteHandler<{ requestId: string; handles: { devto?: string; x?: string; linkedin?: string } }, unknown, { topic: 'content.publish'; data: { requestId: string; userEmail: string; handles?: { devto?: string; x?: string; linkedin?: string } } }>
    'ProcessContent': EventHandler<{ requestId: string; userEmail: string; youtubeUrl: string }, never>
    'HandleApproval': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetContent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'WaitForApproval': EventHandler<{ requestId: string }, never>
    'TriggerContentCreation': ApiRouteHandler<{ youtubeUrl: string; userEmail: string }, unknown, { topic: 'content.requested'; data: { requestId: string; userEmail: string; youtubeUrl: string } }>
  }
    
}