/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'PublishContent': EventHandler<{ requestId: string; userEmail: string; blogPost: string; tweet: string; linkedinPost: string }, never>
    'ProcessContent': EventHandler<never, { topic: 'content.generated'; data: { requestId: string; userEmail: string; blogPost: string; tweet: string; linkedinPost: string } }>
    'HandleApproval': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'content.publish'; data: { requestId: string; userEmail: string; blogPost: string; tweet: string; linkedinPost: string } }>
    'WaitForApproval': EventHandler<{ requestId: string; userEmail: string; blogPost: string; tweet: string; linkedinPost: string }, never>
    'TriggerContentCreation': ApiRouteHandler<{ youtubeUrl: string; userEmail: string }, unknown, { topic: 'content.requested'; data: never }>
  }
    
}